version: "3.3"

# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    mariadb:
      image: mariadb:${MARIADB_VERSION}
      working_dir: /application
      restart: always
      volumes:
        - maria_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "${MYSQL_PORT}:3306"

    phpmyadmin:
      depends_on: 
        - mariadb
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - "${PMA_HTTP_PORT}:80"
      volumes:
        - pma_sessions:/sessions

    # PostgreSQL
    pgdb:
      image: postgres:${POSTGRES_VERSION}
      restart: always
      working_dir: /application
      ports: 
        - "${POSTGRES_PORT}:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}      

    # pgAdmin4
    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      volumes:
        - pgadmin:/var/lib/pgadmin
        - "${PGADMIN_SERVER_JSON_FILE}:/pgadmin4/servers.json"
      depends_on:
        - pgdb
      environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "${PGADMIN_PUBLIC_PORT}:80"        

    # --------------------------------------------------------------------------------
    # WEB SERVER
    # --------------------------------------------------------------------------------

    webserver:
      image: nginx:alpine
      working_dir: /application
      restart: always
      volumes:
          - ./app:/application
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
       - "${NGINX_HTTP_PORT}:80"

    php-fpm:
      image: phpdockerio/symfony-hi
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini'

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  pg_data:
  maria_data:
  pgadmin:
  pma_sessions:
